/*
 * AllOptionsForm.java
 *
 * Created on 30 mars 2008, 18:47
 */
package net.atomique.ksar;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author  alex
 */
public class AllOptionsForm extends javax.swing.JInternalFrame {

    public static final long serialVersionUID = 501L;
    private File sshIdentity;
    private File backgroundImage;
    
    /** Creates new form AllOptionsForm */
    public AllOptionsForm(final kSarDesktop hisdesktop) {
        super();
        mydesktop = hisdesktop;
        initComponents();        
        
        ActionListener actionListener = new ActionListener() {

            public void actionPerformed(final ActionEvent actionEvent) {
                Object source = actionEvent.getSource();
                String lafClassName = null;
                if (source instanceof JComboBox) {
                    JComboBox comboBox = (JComboBox) source;
                    lafClassName = (String) comboBox.getSelectedItem();
                }
                if (lafClassName != null) {
                    String finalLafClassName = lafClassName;
                    for (UIManager.LookAndFeelInfo laf : UIManager.getInstalledLookAndFeels()) {
                        if (lafClassName.equals(laf.getName())) {
                            try {
                                UIManager.setLookAndFeel(laf.getClassName());
                                SwingUtilities.updateComponentTreeUI(mydesktop);
                            } catch (Exception e) {
                            }

                        }
                    }
                }
            }
        };
        load_landf();
        resetButtonActionPerformed(null);
        jComboBox1.addActionListener(actionListener);
        
        this.refreshConfiguration();
    }

    private void refreshConfiguration() {
        this.jSpinner1.setValue(new Integer(kSarConfig.imagewidth));
        this.jSpinner2.setValue(new Integer(kSarConfig.imageheight));
        this.jCheckBox1.setSelected(kSarConfig.imagehtml);
        this.jCheckBox2.setSelected(kSarConfig.ssh_stricthostchecking);
        this.jTextField3.setText(kSarConfig.pdfbottomleft);
        this.jTextField4.setText(kSarConfig.pdfupperright);
        this.jTextField5.setText(kSarConfig.pdfindexpage);
        this.jTextField1.setText(kSarConfig.getBackground_image());
        this.jTextField2.setText(kSarConfig.getBackground_image());
        this.jComboBox1.setSelectedItem(kSarConfig.landf);
        
        if (kSarConfig.sshidentity != null && kSarConfig.sshidentity.exists()) {
            jTextField2.setText(kSarConfig.sshidentity.toString());
        }
        
        if (kSarConfig.background_image != null && kSarConfig.background_image.exists()) {
            jTextField1.setText(kSarConfig.background_image.toString());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();

        setClosable(true);
        setTitle("Options"); // NOI18N
        setPreferredSize(new java.awt.Dimension(430, 438));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setLabelFor(jTextField1);
        jLabel1.setText("Image Width: "); // NOI18N
        jPanel5.add(jLabel1);

        jSpinner1.setValue(new Integer(kSarConfig.imagewidth));
        jPanel5.add(jSpinner1);

        jPanel3.add(jPanel5);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("Image Height: "); // NOI18N
        jPanel4.add(jLabel2);

        jSpinner2.setValue(new Integer(kSarConfig.imageheight));
        jPanel4.add(jSpinner2);

        jPanel3.add(jPanel4);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setText("make HTML index"); // NOI18N
        jPanel6.add(jLabel3);
        jPanel6.add(jCheckBox1);

        jPanel3.add(jPanel6);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setText("PDF bottom left text:"); // NOI18N
        jPanel7.add(jLabel4);

        jTextField3.setText(kSarConfig.pdfbottomleft);
        jTextField3.setMinimumSize(new java.awt.Dimension(150, 22));
        jTextField3.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel7.add(jTextField3);

        jPanel3.add(jPanel7);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel5.setText("PDF upper right text: "); // NOI18N
        jPanel8.add(jLabel5);

        jTextField4.setText(kSarConfig.pdfupperright);
        jTextField4.setMinimumSize(new java.awt.Dimension(150, 22));
        jTextField4.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel8.add(jTextField4);

        jPanel3.add(jPanel8);

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel6.setText("PDF index page text: "); // NOI18N
        jPanel9.add(jLabel6);

        jTextField5.setText(kSarConfig.pdfindexpage);
        jTextField5.setMinimumSize(new java.awt.Dimension(150, 22));
        jTextField5.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel9.add(jTextField5);

        jPanel3.add(jPanel9);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel7.setText("Background image File: "); // NOI18N
        jPanel10.add(jLabel7);

        jTextField1.setEditable(false);
        jTextField1.setText(kSarConfig.getBackground_image());
        jTextField1.setMinimumSize(new java.awt.Dimension(150, 22));
        jTextField1.setPreferredSize(new java.awt.Dimension(150, 22));
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jPanel10.add(jTextField1);

        jPanel3.add(jPanel10);

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel8.setText("SSH key file"); // NOI18N
        jPanel11.add(jLabel8);

        jTextField2.setEditable(false);
        jTextField2.setText(kSarConfig.getSSHidentity());
        jTextField2.setMinimumSize(new java.awt.Dimension(150, 22));
        jTextField2.setPreferredSize(new java.awt.Dimension(150, 22));
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jPanel11.add(jTextField2);

        jPanel3.add(jPanel11);

        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel9.setText("Look&Feel");
        jPanel12.add(jLabel9);

        jComboBox1.setModel(model);
        jPanel12.add(jComboBox1);

        jPanel3.add(jPanel12);

        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel10.setText("SSH strict host checking ");
        jPanel13.add(jLabel10);

        jCheckBox2.setSelected(true);
        jPanel13.add(jCheckBox2);

        jPanel3.add(jPanel13);

        jScrollPane1.setViewportView(jPanel3);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        okButton.setText("Ok"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        jPanel2.add(okButton);

        cancelButton.setText("Cancel"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel2.add(cancelButton);

        resetButton.setText("Reset"); // NOI18N
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        jPanel2.add(resetButton);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(true);
        this.dispose();
}//GEN-LAST:event_cancelButtonActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        BackgroundImageSelector selector = new BackgroundImageSelector();
        File file = selector.chooseBackgroundFile();
        
        if (file != null) {
            this.backgroundImage = file;
            jTextField1.setText(file.toString());
        }
 
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        SSHIdentitySelector sshIdentiyChooser = new SSHIdentitySelector();
        File file = sshIdentiyChooser.selectIdentity();
        
        if (file != null) {
            this.sshIdentity = file;
            this.jTextField2.setText(file.toString());
        }
    }//GEN-LAST:event_jTextField2MouseClicked

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        Integer tmp;
        tmp = new Integer(jSpinner1.getValue().toString());
        kSarConfig.imagewidth = tmp.intValue();
        tmp = new Integer(jSpinner2.getValue().toString());
        kSarConfig.imageheight = tmp.intValue();
        kSarConfig.imagehtml = jCheckBox1.isSelected();
        kSarConfig.pdfbottomleft = jTextField3.getText();
        kSarConfig.pdfupperright = jTextField4.getText();
        kSarConfig.pdfindexpage = jTextField5.getText();
        kSarConfig.landf = jComboBox1.getSelectedItem().toString();
        kSarConfig.ssh_stricthostchecking = jCheckBox2.isSelected();
        
        if (this.sshIdentity != null) {
            kSarConfig.sshidentity = this.sshIdentity;
        }
        
        if (this.backgroundImage != null) {
            kSarConfig.background_image = this.backgroundImage;
        }
        
        kSarConfig.writeDefault();
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        this.refreshConfiguration();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void load_landf() {
        UIManager.LookAndFeelInfo looks[] = UIManager.getInstalledLookAndFeels();
        for (int i = 0,  n = looks.length; i < n; i++) {
            String tmp = looks[i].getName();
            model.addElement(tmp);
            if (kSarConfig.landf.equals(tmp)) {
                jComboBox1.setSelectedItem(tmp);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton okButton;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables
    DefaultComboBoxModel model = new DefaultComboBoxModel();
    kSarDesktop mydesktop;
}
