/*
 * CalendarSelection.java
 *
 * Created on 22 juin 2008, 15:05
 */
package net.atomique.ksar;

import javax.swing.DefaultListModel;
import org.jfree.data.time.Second;

/**
 *
 * @author  alex
 */
public class CalendarSelection extends javax.swing.JFrame {

    public static final long serialVersionUID = 501L;
    
    /** Creates new form CalendarSelection */
    public CalendarSelection(kSar hissar) {
        mysar = hissar;
        load_datefound();
        initComponents();
        
        liststart.setSelectedValue(mysar.startofgraph,true);
        listend.setSelectedValue(mysar.endofgraph, true);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        liststart = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listend = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        OkButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calendar");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel1.setText("start at:");
        jPanel5.add(jLabel1);

        liststart.setModel(mytimeList);
        liststart.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        liststart.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                liststartValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(liststart);

        jPanel5.add(jScrollPane1);

        jPanel2.add(jPanel5);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel2.setText("end at:");
        jPanel4.add(jLabel2);

        listend.setModel(mytimeList);
        listend.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listendValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listend);

        jPanel4.add(jScrollPane2);

        jPanel2.add(jPanel4);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        OkButton.setText("Ok");
        OkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButtonActionPerformed(evt);
            }
        });
        jPanel3.add(OkButton);

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        jPanel3.add(resetButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel3.add(cancelButton);

        jPanel1.add(jPanel3, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
        dispose();                       
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        liststart.setSelectedValue(mysar.statstart, true);
        listend.setSelectedValue(mysar.statend, true);
        if (mysar.myUI.obj2 != null) {
            mysar.myUI.chartContainer.removeAll();
            mysar.myUI.chartContainer.add(mysar.myUI.obj2.run(mysar.startofgraph, mysar.endofgraph));
        }
    }//GEN-LAST:event_resetButtonActionPerformed

    private void OkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkButtonActionPerformed

        mysar.startofgraph = (Second)liststart.getSelectedValue();
        mysar.endofgraph = (Second)listend.getSelectedValue();
        setVisible(false);
        dispose();

        if (mysar.myUI.obj2 != null) {
            mysar.isparsing = false;
            mysar.myUI.chartContainer.removeAll();
            mysar.myUI.chartContainer.add(mysar.myUI.obj2.run(mysar.startofgraph, mysar.endofgraph));
            mysar.myUI.chartContainer.validate();
        }
    }//GEN-LAST:event_OkButtonActionPerformed

    private void liststartValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_liststartValueChanged
        if (!evt.getValueIsAdjusting()) {
            
            Second a = (Second)listend.getSelectedValue();
            Second b = (Second)liststart.getSelectedValue();
            if ( a == null || b == null)  {
                return;
            }
            if (a.compareTo(b) <= 0) {
                liststart.setSelectedValue(mysar.startofgraph, true);
            } else {
                mysar.startofgraph = (Second)liststart.getSelectedValue();
            }
        }
    }//GEN-LAST:event_liststartValueChanged

    private void listendValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listendValueChanged
        if (!evt.getValueIsAdjusting()) {
            Second a = Second.parseSecond(listend.getSelectedValue().toString());
            Second b = Second.parseSecond(liststart.getSelectedValue().toString());
            if ( a == null || b == null)  {
                return;
            }
            if (b.compareTo(a) >= 0) {
                listend.setSelectedValue(mysar.endofgraph, true);
            } else {
                mysar.endofgraph = (Second)listend.getSelectedValue();
            }
        }
    }//GEN-LAST:event_listendValueChanged

    private void load_datefound() {
        for (int i = 0; i < mysar.datefound.size(); i++) {
            mytimeList.addElement(mysar.datefound.get(i));
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OkButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listend;
    private javax.swing.JList liststart;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables
    kSar mysar;
    DefaultListModel mytimeList=new DefaultListModel();
    
}
