/*
 * LineColorChooser.java
 *
 * Created on 24 juillet 2008, 17:05
 */
package net.atomique.ksar;

import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JTextField;

/**
 *
 * @author  alex
 */
public class LineColorChooser extends javax.swing.JDialog {

    public static final long serialVersionUID = 501L;
    
    /** Creates new form LineColorChooser */
    public LineColorChooser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        load_color();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelcolor1 = new javax.swing.JPanel();
        labelcolor1 = new javax.swing.JLabel();
        boxcolor1 = new javax.swing.JTextField();
        panelcolor2 = new javax.swing.JPanel();
        labelcolor2 = new javax.swing.JLabel();
        boxcolor2 = new javax.swing.JTextField();
        panelcolor3 = new javax.swing.JPanel();
        labelcolor3 = new javax.swing.JLabel();
        boxcolor3 = new javax.swing.JTextField();
        panelcolor4 = new javax.swing.JPanel();
        labelcolor4 = new javax.swing.JLabel();
        boxcolor4 = new javax.swing.JTextField();
        panelcolor5 = new javax.swing.JPanel();
        labelcolor5 = new javax.swing.JLabel();
        boxcolor5 = new javax.swing.JTextField();
        panelcolor6 = new javax.swing.JPanel();
        labelcolor6 = new javax.swing.JLabel();
        boxcolor6 = new javax.swing.JTextField();
        panelcolor7 = new javax.swing.JPanel();
        labelcolor7 = new javax.swing.JLabel();
        boxcolor7 = new javax.swing.JTextField();
        panelcolor8 = new javax.swing.JPanel();
        labelcolor8 = new javax.swing.JLabel();
        boxcolor8 = new javax.swing.JTextField();
        panelcolor9 = new javax.swing.JPanel();
        labelcolor9 = new javax.swing.JLabel();
        boxcolor9 = new javax.swing.JTextField();
        panelcolor10 = new javax.swing.JPanel();
        labelcolor10 = new javax.swing.JLabel();
        boxcolor10 = new javax.swing.JTextField();
        panelcolor11 = new javax.swing.JPanel();
        labelcolor11 = new javax.swing.JLabel();
        boxcolor11 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        resetButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Choose Line Color");
        setAlwaysOnTop(true);
        setName("colordialog"); // NOI18N
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        panelcolor1.setLayout(new java.awt.GridLayout(1, 5, 5, 5));

        labelcolor1.setText("Line Type 1");
        panelcolor1.add(labelcolor1);

        boxcolor1.setBackground(new java.awt.Color(255, 51, 0));
        boxcolor1.setColumns(5);
        boxcolor1.setEditable(false);
        boxcolor1.setText("     ");
        boxcolor1.setEnabled(false);
        boxcolor1.setFocusable(false);
        boxcolor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorchanger(evt);
            }
        });
        panelcolor1.add(boxcolor1);

        jPanel1.add(panelcolor1);

        panelcolor2.setLayout(new java.awt.GridLayout(1, 5, 5, 5));

        labelcolor2.setText("Line Type 2");
        panelcolor2.add(labelcolor2);

        boxcolor2.setBackground(new java.awt.Color(255, 51, 0));
        boxcolor2.setColumns(5);
        boxcolor2.setEditable(false);
        boxcolor2.setText("     ");
        boxcolor2.setEnabled(false);
        boxcolor2.setFocusable(false);
        boxcolor2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorchanger(evt);
            }
        });
        panelcolor2.add(boxcolor2);

        jPanel1.add(panelcolor2);

        panelcolor3.setLayout(new java.awt.GridLayout(1, 5, 5, 5));

        labelcolor3.setText("Line Type 3");
        panelcolor3.add(labelcolor3);

        boxcolor3.setBackground(new java.awt.Color(255, 51, 0));
        boxcolor3.setColumns(5);
        boxcolor3.setEditable(false);
        boxcolor3.setText("     ");
        boxcolor3.setEnabled(false);
        boxcolor3.setFocusable(false);
        boxcolor3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorchanger(evt);
            }
        });
        panelcolor3.add(boxcolor3);

        jPanel1.add(panelcolor3);

        panelcolor4.setLayout(new java.awt.GridLayout(1, 5, 5, 5));

        labelcolor4.setText("Line Type 4");
        panelcolor4.add(labelcolor4);

        boxcolor4.setBackground(new java.awt.Color(255, 51, 0));
        boxcolor4.setColumns(5);
        boxcolor4.setEditable(false);
        boxcolor4.setText("     ");
        boxcolor4.setEnabled(false);
        boxcolor4.setFocusable(false);
        boxcolor4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorchanger(evt);
            }
        });
        panelcolor4.add(boxcolor4);

        jPanel1.add(panelcolor4);

        panelcolor5.setLayout(new java.awt.GridLayout(1, 5, 5, 5));

        labelcolor5.setText("Line Type 5");
        panelcolor5.add(labelcolor5);

        boxcolor5.setBackground(new java.awt.Color(255, 51, 0));
        boxcolor5.setColumns(5);
        boxcolor5.setEditable(false);
        boxcolor5.setText("     ");
        boxcolor5.setEnabled(false);
        boxcolor5.setFocusable(false);
        boxcolor5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxcolor5ActionPerformed(evt);
            }
        });
        boxcolor5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorchanger(evt);
            }
        });
        panelcolor5.add(boxcolor5);

        jPanel1.add(panelcolor5);

        panelcolor6.setLayout(new java.awt.GridLayout(1, 5, 5, 5));

        labelcolor6.setText("Line Type 6");
        panelcolor6.add(labelcolor6);

        boxcolor6.setBackground(new java.awt.Color(255, 51, 0));
        boxcolor6.setColumns(5);
        boxcolor6.setEditable(false);
        boxcolor6.setText("     ");
        boxcolor6.setEnabled(false);
        boxcolor6.setFocusable(false);
        boxcolor6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorchanger(evt);
            }
        });
        panelcolor6.add(boxcolor6);

        jPanel1.add(panelcolor6);

        panelcolor7.setLayout(new java.awt.GridLayout(1, 5, 5, 5));

        labelcolor7.setText("Line Type 7");
        panelcolor7.add(labelcolor7);

        boxcolor7.setBackground(new java.awt.Color(255, 51, 0));
        boxcolor7.setColumns(5);
        boxcolor7.setEditable(false);
        boxcolor7.setText("     ");
        boxcolor7.setEnabled(false);
        boxcolor7.setFocusable(false);
        boxcolor7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorchanger(evt);
            }
        });
        panelcolor7.add(boxcolor7);

        jPanel1.add(panelcolor7);

        panelcolor8.setLayout(new java.awt.GridLayout(1, 5, 5, 5));

        labelcolor8.setText("Line Type 8");
        panelcolor8.add(labelcolor8);

        boxcolor8.setBackground(new java.awt.Color(255, 51, 0));
        boxcolor8.setColumns(5);
        boxcolor8.setEditable(false);
        boxcolor8.setText("     ");
        boxcolor8.setEnabled(false);
        boxcolor8.setFocusable(false);
        boxcolor8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorchanger(evt);
            }
        });
        panelcolor8.add(boxcolor8);

        jPanel1.add(panelcolor8);

        panelcolor9.setLayout(new java.awt.GridLayout(1, 5, 5, 5));

        labelcolor9.setText("Line Type 9");
        panelcolor9.add(labelcolor9);

        boxcolor9.setBackground(new java.awt.Color(255, 51, 0));
        boxcolor9.setColumns(5);
        boxcolor9.setEditable(false);
        boxcolor9.setText("     ");
        boxcolor9.setEnabled(false);
        boxcolor9.setFocusable(false);
        boxcolor9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorchanger(evt);
            }
        });
        panelcolor9.add(boxcolor9);

        jPanel1.add(panelcolor9);

        panelcolor10.setLayout(new java.awt.GridLayout(1, 5, 5, 5));

        labelcolor10.setText("Line Type 10");
        panelcolor10.add(labelcolor10);

        boxcolor10.setBackground(new java.awt.Color(255, 51, 0));
        boxcolor10.setColumns(5);
        boxcolor10.setEditable(false);
        boxcolor10.setText("     ");
        boxcolor10.setEnabled(false);
        boxcolor10.setFocusable(false);
        boxcolor10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorchanger(evt);
            }
        });
        panelcolor10.add(boxcolor10);

        jPanel1.add(panelcolor10);

        panelcolor11.setLayout(new java.awt.GridLayout(1, 5, 5, 5));

        labelcolor11.setText("Line Type 11");
        panelcolor11.add(labelcolor11);

        boxcolor11.setBackground(new java.awt.Color(255, 51, 0));
        boxcolor11.setColumns(5);
        boxcolor11.setEditable(false);
        boxcolor11.setText("     ");
        boxcolor11.setEnabled(false);
        boxcolor11.setFocusable(false);
        boxcolor11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxcolor11colorchanger(evt);
            }
        });
        panelcolor11.add(boxcolor11);

        jPanel1.add(panelcolor11);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        resetButton.setText("Reset to defaults");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        jPanel2.add(resetButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel2.add(cancelButton);

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        jPanel2.add(okButton);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void boxcolor5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxcolor5ActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_boxcolor5ActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        save_color();
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void colorchanger(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorchanger
        if ( evt == null ) {
            return;
        }
        if (evt.getSource() instanceof JTextField) {
            JTextField tmp = (JTextField) evt.getSource();
            Color tmpcolor = JColorChooser.showDialog(this, "Choose Background Color", tmp.getBackground());
            if (tmpcolor != null) {
                tmp.setBackground(tmpcolor);
            }
        }        
    }//GEN-LAST:event_colorchanger

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        reset_color();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void boxcolor11colorchanger(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxcolor11colorchanger
        // TODO add your handling code here:
    }//GEN-LAST:event_boxcolor11colorchanger

    private void reset_color() {
        kSarConfig.color1 = Color.BLUE;
        kSarConfig.color2 = Color.GREEN;
        kSarConfig.color3 = Color.RED;
        kSarConfig.color4 = Color.BLACK;
        kSarConfig.color5 = Color.MAGENTA;
        kSarConfig.color6 = Color.YELLOW;
        kSarConfig.color7 = Color.CYAN;
        kSarConfig.color8 = Color.GRAY;
        kSarConfig.color9 = Color.ORANGE;
        kSarConfig.color10 = Color.PINK;
        kSarConfig.color11 = Color.DARK_GRAY;
        kSarConfig.writeDefault();
        load_color();
    }
    
    private void load_color() {
        // load color from config
        boxcolor1.setBackground(kSarConfig.color1);
        boxcolor2.setBackground(kSarConfig.color2);
        boxcolor3.setBackground(kSarConfig.color3);
        boxcolor4.setBackground(kSarConfig.color4);
        boxcolor5.setBackground(kSarConfig.color5);
        boxcolor6.setBackground(kSarConfig.color6);
        boxcolor7.setBackground(kSarConfig.color7);
        boxcolor8.setBackground(kSarConfig.color8);
        boxcolor9.setBackground(kSarConfig.color9);
        boxcolor10.setBackground(kSarConfig.color10);
        boxcolor11.setBackground(kSarConfig.color11);
    }

    private void save_color() {
        // save color to config
        kSarConfig.color1 = boxcolor1.getBackground();
        kSarConfig.color2 = boxcolor2.getBackground();
        kSarConfig.color3 = boxcolor3.getBackground();
        kSarConfig.color4 = boxcolor4.getBackground();
        kSarConfig.color5 = boxcolor5.getBackground();
        kSarConfig.color6 = boxcolor6.getBackground();
        kSarConfig.color7 = boxcolor7.getBackground();
        kSarConfig.color8 = boxcolor8.getBackground();
        kSarConfig.color9 = boxcolor9.getBackground();
        kSarConfig.color10 = boxcolor10.getBackground();
        kSarConfig.color11 = boxcolor11.getBackground();
        kSarConfig.writeDefault();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                LineColorChooser dialog = new LineColorChooser(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField boxcolor1;
    private javax.swing.JTextField boxcolor10;
    private javax.swing.JTextField boxcolor11;
    private javax.swing.JTextField boxcolor2;
    private javax.swing.JTextField boxcolor3;
    private javax.swing.JTextField boxcolor4;
    private javax.swing.JTextField boxcolor5;
    private javax.swing.JTextField boxcolor6;
    private javax.swing.JTextField boxcolor7;
    private javax.swing.JTextField boxcolor8;
    private javax.swing.JTextField boxcolor9;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelcolor1;
    private javax.swing.JLabel labelcolor10;
    private javax.swing.JLabel labelcolor11;
    private javax.swing.JLabel labelcolor2;
    private javax.swing.JLabel labelcolor3;
    private javax.swing.JLabel labelcolor4;
    private javax.swing.JLabel labelcolor5;
    private javax.swing.JLabel labelcolor6;
    private javax.swing.JLabel labelcolor7;
    private javax.swing.JLabel labelcolor8;
    private javax.swing.JLabel labelcolor9;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel panelcolor1;
    private javax.swing.JPanel panelcolor10;
    private javax.swing.JPanel panelcolor11;
    private javax.swing.JPanel panelcolor2;
    private javax.swing.JPanel panelcolor3;
    private javax.swing.JPanel panelcolor4;
    private javax.swing.JPanel panelcolor5;
    private javax.swing.JPanel panelcolor6;
    private javax.swing.JPanel panelcolor7;
    private javax.swing.JPanel panelcolor8;
    private javax.swing.JPanel panelcolor9;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables
    
}
