/*
 * AllOptionsForm.java
 *
 * Created on 30 mars 2008, 18:47
 */

package net.atomique.ksar;

/**
 *
 * @author  alex
 */
public class LinuxTrigger extends javax.swing.JInternalFrame {
    
    public static final long serialVersionUID = 501L;
    
    /** Creates new form AllOptionsForm */
    public LinuxTrigger() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();

        setClosable(true);
        setTitle("Options"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setText("CPU idle minimum:"); // NOI18N
        jPanel7.add(jLabel4);

        jTextField3.setText(kSarConfig.linuxcpuidletrigger.toString());
        jTextField3.setMinimumSize(new java.awt.Dimension(150, 22));
        jTextField3.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel7.add(jTextField3);

        jPanel3.add(jPanel7);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel5.setText("CPU system maximum: "); // NOI18N
        jPanel8.add(jLabel5);

        jTextField4.setText(kSarConfig.linuxcpusystemtrigger.toString());
        jTextField4.setMinimumSize(new java.awt.Dimension(150, 22));
        jTextField4.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel8.add(jTextField4);

        jPanel3.add(jPanel8);

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel6.setText("CPU I/O maximum"); // NOI18N
        jPanel9.add(jLabel6);

        jTextField5.setText(kSarConfig.linuxcpuwiotrigger.toString());
        jTextField5.setMinimumSize(new java.awt.Dimension(150, 22));
        jTextField5.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel9.add(jTextField5);

        jPanel3.add(jPanel9);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel7.setText("CPU user maximum"); // NOI18N
        jPanel10.add(jLabel7);

        jTextField1.setEditable(false);
        jTextField1.setText(kSarConfig.linuxcpuusrtrigger.toString());
        jTextField1.setMinimumSize(new java.awt.Dimension(150, 22));
        jTextField1.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel10.add(jTextField1);

        jPanel3.add(jPanel10);

        jScrollPane1.setViewportView(jPanel3);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        okButton.setText("Ok"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        jPanel2.add(okButton);

        cancelButton.setText("Cancel"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel2.add(cancelButton);

        resetButton.setText("Reset"); // NOI18N
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        jPanel2.add(resetButton);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(true);
        this.dispose();
}//GEN-LAST:event_cancelButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        jTextField3.setText(kSarConfig.linuxcpuidletrigger.toString());
        jTextField4.setText(kSarConfig.linuxcpusystemtrigger.toString());
        jTextField5.setText(kSarConfig.linuxcpuwiotrigger.toString());
        jTextField1.setText(kSarConfig.linuxcpuusrtrigger.toString());
    }//GEN-LAST:event_resetButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        kSarConfig.linuxcpuidletrigger= new Double(jTextField3.getText());
        kSarConfig.linuxcpusystemtrigger = new Double(jTextField4.getText());
        kSarConfig.linuxcpuwiotrigger = new Double(jTextField5.getText());
        kSarConfig.linuxcpuusrtrigger = new Double(jTextField1.getText());
        kSarConfig.writeDefault();
        setVisible(true);
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton okButton;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables
    
}
