/*
 * pdfOptions.java
 *
 * Created on 1 mars 2008, 17:48
 */
package net.atomique.ksar;

/**
 *
 * @author  alex
 */
public class pdfOptions extends javax.swing.JInternalFrame {

    public static final long serialVersionUID = 501L;
    
    /** Creates new form pdfOptions */
    public pdfOptions() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        optionpanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelinfo = new javax.swing.JPanel();
        panelname = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelvalue = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setClosable(true);
        setTitle("PDF Options");
        setPreferredSize(new java.awt.Dimension(450, 280));

        jPanel1.setLayout(new java.awt.BorderLayout());

        optionpanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        optionpanel.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 200));

        panelname.setLayout(new java.awt.GridLayout(0, 1));

        jLabel1.setLabelFor(jTextField1);
        jLabel1.setText("PDF Bottom Left: ");
        panelname.add(jLabel1);

        jLabel2.setLabelFor(jTextField2);
        jLabel2.setText("PDF Upper Right: ");
        panelname.add(jLabel2);

        jLabel3.setLabelFor(jTextField3);
        jLabel3.setText("PDF Index Page: ");
        panelname.add(jLabel3);

        panelinfo.add(panelname);

        panelvalue.setLayout(new java.awt.GridLayout(0, 1));

        jTextField3.setColumns(30);
        jTextField3.setText(kSarConfig.pdfbottomleft);
        panelvalue.add(jTextField3);

        jTextField2.setColumns(30);
        jTextField2.setText(kSarConfig.pdfupperright);
        panelvalue.add(jTextField2);

        jTextField1.setColumns(30);
        jTextField1.setText(kSarConfig.pdfindexpage);
        panelvalue.add(jTextField1);

        panelinfo.add(panelvalue);

        jScrollPane1.setViewportView(panelinfo);

        optionpanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(optionpanel, java.awt.BorderLayout.PAGE_START);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        jPanel2.add(okButton);

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        jPanel2.add(resetButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel2.add(cancelButton);

        jPanel1.add(jPanel2, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        jTextField1.setText(kSarConfig.pdfindexpage);
        jTextField2.setText(kSarConfig.pdfupperright);
        jTextField3.setText(kSarConfig.pdfbottomleft);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        boolean tosave = false;
        String tmp;
        tmp = jTextField1.getText();
        if (! kSarConfig.pdfindexpage.equals(tmp)) {
            kSarConfig.pdfindexpage = tmp;
            tosave = true;
        }
        tmp = jTextField3.getText();
        if (! kSarConfig.pdfbottomleft.equals(tmp)) {
            kSarConfig.pdfbottomleft = tmp;
            tosave = true;
        }
        tmp = jTextField2.getText();
        if (! kSarConfig.pdfupperright.equals(tmp)) {
            kSarConfig.pdfupperright = tmp;
            tosave = true;
        }
        setVisible(false);
        dispose();
        if (tosave) {
            kSarConfig.writeDefault();
        }
    }//GEN-LAST:event_okButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel optionpanel;
    private javax.swing.JPanel panelinfo;
    private javax.swing.JPanel panelname;
    private javax.swing.JPanel panelvalue;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables
}
