/*
 * AllOptionsForm.java
 *
 * Created on 30 mars 2008, 18:47
 */

package net.atomique.ksar;

/**
 *
 * @author  alex
 */
public class SolarisTrigger extends javax.swing.JInternalFrame {
    
    public static final long serialVersionUID = 501L;
    
    /** Creates new form AllOptionsForm */
    public SolarisTrigger() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();

        setClosable(true);
        setTitle("Options"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setText("CPU idle minimum:"); // NOI18N
        jPanel7.add(jLabel4);

        jTextField3.setText(kSarConfig.solariscpuidletrigger.toString());
        jTextField3.setMinimumSize(new java.awt.Dimension(150, 22));
        jTextField3.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel7.add(jTextField3);

        jPanel3.add(jPanel7);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel5.setText("CPU system maximum: "); // NOI18N
        jPanel8.add(jLabel5);

        jTextField4.setText(kSarConfig.solariscpusystemtrigger.toString());
        jTextField4.setMinimumSize(new java.awt.Dimension(150, 22));
        jTextField4.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel8.add(jTextField4);

        jPanel3.add(jPanel8);

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel6.setText("CPU I/O maximum"); // NOI18N
        jPanel9.add(jLabel6);

        jTextField5.setText(kSarConfig.solariscpuwiotrigger.toString());
        jTextField5.setMinimumSize(new java.awt.Dimension(150, 22));
        jTextField5.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel9.add(jTextField5);

        jPanel3.add(jPanel9);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel7.setText("CPU user maximum"); // NOI18N
        jPanel10.add(jLabel7);

        jTextField1.setEditable(false);
        jTextField1.setText(kSarConfig.solariscpuusrtrigger.toString());
        jTextField1.setMinimumSize(new java.awt.Dimension(150, 22));
        jTextField1.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel10.add(jTextField1);

        jPanel3.add(jPanel10);

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel8.setText("Disk %busy maximum: "); // NOI18N
        jPanel11.add(jLabel8);

        jTextField2.setEditable(false);
        jTextField2.setText(kSarConfig.solarisdiskbusytrigger.toString());
        jTextField2.setMinimumSize(new java.awt.Dimension(150, 22));
        jTextField2.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel11.add(jTextField2);

        jPanel3.add(jPanel11);

        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel9.setText("Disk avserv maximum:"); // NOI18N
        jPanel12.add(jLabel9);

        jTextField6.setEditable(false);
        jTextField6.setText(kSarConfig.solarisdiskavservtrigger.toString());
        jTextField6.setMinimumSize(new java.awt.Dimension(150, 22));
        jTextField6.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel12.add(jTextField6);

        jPanel3.add(jPanel12);

        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel10.setText("Disk avque maximum:"); // NOI18N
        jPanel13.add(jLabel10);

        jTextField7.setEditable(false);
        jTextField7.setText(kSarConfig.solarisdiskavquetrigger.toString());
        jTextField7.setMinimumSize(new java.awt.Dimension(150, 22));
        jTextField7.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel13.add(jTextField7);

        jPanel3.add(jPanel13);

        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel11.setText("Buffer %read cache minimum:"); // NOI18N
        jPanel14.add(jLabel11);

        jTextField8.setEditable(false);
        jTextField8.setText(kSarConfig.solarisbufferrcachetrigger.toString());
        jTextField8.setMinimumSize(new java.awt.Dimension(150, 22));
        jTextField8.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel14.add(jTextField8);

        jPanel3.add(jPanel14);

        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel12.setText("Run Queue Size maximum:"); // NOI18N
        jPanel15.add(jLabel12);

        jTextField9.setEditable(false);
        jTextField9.setText(kSarConfig.solarisrqueuetrigger.toString());
        jTextField9.setMinimumSize(new java.awt.Dimension(150, 22));
        jTextField9.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel15.add(jTextField9);

        jPanel3.add(jPanel15);

        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel13.setText("Page Scan maximum:"); // NOI18N
        jPanel16.add(jLabel13);

        jTextField10.setEditable(false);
        jTextField10.setText(kSarConfig.solarispagescantrigger.toString());
        jTextField10.setMinimumSize(new java.awt.Dimension(150, 22));
        jTextField10.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel16.add(jTextField10);

        jPanel3.add(jPanel16);

        jScrollPane1.setViewportView(jPanel3);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        okButton.setText("Ok"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        jPanel2.add(okButton);

        cancelButton.setText("Cancel"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel2.add(cancelButton);

        resetButton.setText("Reset"); // NOI18N
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        jPanel2.add(resetButton);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(true);
        this.dispose();
}//GEN-LAST:event_cancelButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        jTextField3.setText(kSarConfig.solariscpuidletrigger.toString());
        jTextField4.setText(kSarConfig.solariscpusystemtrigger.toString());
        jTextField5.setText(kSarConfig.solariscpuwiotrigger.toString());
        jTextField1.setText(kSarConfig.solariscpuusrtrigger.toString());
        jTextField2.setText(kSarConfig.solarisdiskbusytrigger.toString());
        jTextField6.setText(kSarConfig.solarisdiskavservtrigger.toString());
        jTextField7.setText(kSarConfig.solarisdiskavquetrigger.toString());
        jTextField8.setText(kSarConfig.solarisbufferrcachetrigger.toString());
        jTextField9.setText(kSarConfig.solarisrqueuetrigger.toString());
        jTextField10.setText(kSarConfig.solarispagescantrigger.toString());
    }//GEN-LAST:event_resetButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        kSarConfig.solariscpuidletrigger= new Double(jTextField3.getText());
        kSarConfig.solariscpusystemtrigger = new Double(jTextField4.getText());
        kSarConfig.solariscpuwiotrigger = new Double(jTextField5.getText());
        kSarConfig.solariscpuusrtrigger = new Double(jTextField1.getText());
        kSarConfig.solarisdiskbusytrigger= new Double(jTextField2.getText());
        kSarConfig.solarisdiskavservtrigger= new Double(jTextField6.getText());
        kSarConfig.solarisdiskavquetrigger= new Double(jTextField7.getText());
        kSarConfig.solarisbufferrcachetrigger= new Double(jTextField8.getText());
        kSarConfig.solarisrqueuetrigger = new Double(jTextField9.getText());
        kSarConfig.solarispagescantrigger=new Double(jTextField10.getText());
        kSarConfig.writeDefault();
        setVisible(true);
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton okButton;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables
    
}
